FROM openjdk:17-jdk-slim

WORKDIR /app

COPY nome-do-arquivo.jar app.jar

EXPOSE 8080

CMD ["java", "-jar", "app.jar"]

# Desta forma conseguimos executar a criação da imagem de um container que irá executar o arquivo JAR
# Para realizarmos a utilização de um arquivo jar dentro do container podemos passar isso através de um exec
# docker exec -it <container_id> java -jar /app/app.jar
# Com isso conseguimos automatizar através de um crontab a execução deste comando que utiliza o arquivo jar
