version: '3.0'

services:
  nginx-proxy:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80" 
    depends_on:
      - frontend
      - backend-login-service
      - backend-gateway-service
      - backend-crud-service
      - backend-ia-service
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro 
    restart: always

  frontend:
    image: mvittu/v8-rh/frontend-node
    ports:
      - "3000:80"
    depends_on:
      - backend-login-service
    restart: always

  backend-login-service:
    image: mvittu/v8-rh/backend-login
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - database
    restart: always

  backend-gateway-service:
    image: mvittu/v8-rh/backend-gateway
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - database
    restart: always

  backend-crud-service:
    image: mvittu/v8-rh/backend-crud
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - database
    restart: always

  backend-ia-service:
    image: mvittu/v8-rh/ia-python
    ports:
      - "8084:8084"
    depends_on:
      - database
    restart: always

  database:
    image: mvittu/v8-rh/bd-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: meubanco
    volumes:
      - db_data:/var/lib/postgresql/data
      - Dockerfiles/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

volumes:
  db_data: